config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "decks#index"

  resources :users do
    resources :decks do
      resources :cards
      resources :subjects
    end
  end

  resources :decks do
    resources :cards do
      collection { post :import } # AWESOME
    end
    resources :subjects
  end

  resources :subjects do
    resources :decks
  end

get '*unmatched_route', to: 'application#not_found' # :+1:

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  require 'csv'

  def self.import(file, deck_id)
    # awesome feature!
    CSV.foreach(file.path,headers: true) do |row|
      @temp = Card.new row.to_hash
      # question: why not make this a model method on Deck?
      @temp.deck_id = deck_id ## ^^
      @temp.save
    end
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards, dependent: :destroy
  has_many :decks_subjects
  has_many :subjects, through: :decks_subjects
end

app/models/deck_subject.rb
class DeckSubject < ActiveRecord::Base
  belongs_to :deck
  belongs_to :subject
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :decks_subjects
  has_many :decks, through: :decks_subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def not_found
  redirect_to decks_path
end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def import
    @deck = Deck.find(params[:deck_id])
    Card.import(params[:file],params[:deck_id])
    flash[:notice] = "File has been imported."
    redirect_to edit_deck_path(@deck)
  end

  def create
      @deck = Deck.find(params[:deck_id])
      @card = @deck.cards.new(card_params)
      @card.save
      redirect_to edit_deck_path(params[:deck_id])
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def show
    @deck = Deck.find(params[:deck_id])
    if @deck.published = false
      redirect_to decks_path
    else
      @leftarrow = "Previous Question"
      @rightarrow = "Next Question"
      if params[:id]
        @card = @deck.cards.find(params[:id])
        if @deck.cards.index(@card) == 0
          @cardprevious = @deck.cards.last
          @cardnext = @deck.cards[@deck.cards.index(@card)+1]
          @leftarrow = "Last Card"
        elsif @deck.cards.index(@card) == @deck.cards.length - 1
          @cardprevious = @deck.cards[@deck.cards.index(@card)-1]
          @cardnext = @deck.cards.first
          @rightarrow = "First Card"
        else
          @cardprevious = @deck.cards[@deck.cards.index(@card)-1]
          @cardnext = @deck.cards[@deck.cards.index(@card)+1]
        end
      else
      @card = @deck.first
      end
    end
  end

  def update
    @card = Card.find(params[:id])
    @deck = @card.deck
    if @card.update(card_params)
      flash[:notice] = "Card has been updated."
      redirect_to edit_deck_path(@deck.id)
    else
      redirect_to edit_deck_path(@deck.id)
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    @deck = @card.deck
    if @deck.cards.length < 5
      @deck.published = false
    end
    @deck.save
    redirect_to edit_deck_path(params[:deck_id])
  end

  private

  def deck_params
    params.require(:deck).permt(:title)
  end

  def card_params
    params.require(:card).permit(:question, :answer)
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index

    if params[:user_id]
      @user = current_user
      @decks = @user.decks.all
      @deck = @user.decks.new
      redirect_to new_user_deck_path
    else
      @decks = Deck.where(:published => true)
      @deck = Deck.new
    end
  end

  def create
    @user = current_user
    @deck = @user.decks.new(deck_params)
    @deck.last_touched = DateTime.now
    if @deck.save
      flash[:notice] = "#{@deck.title} was successfully created."
      @deck.last_touched = DateTime.now.to_date
      redirect_to user_decks_path
    else
      redirect_to user_decks_path
    end
  end

  def new
    if params[:user_id]
      @user = current_user
      @deck = @user.decks.new
      @card = @deck.cards.new
      @decks = @user.decks.all
    else
      flash[:alert] = "You must be signed in to create a deck"
      redirect_to root
    end
  end

  def edit
    @user = current_user
    @deck = Deck.find(params[:id])
    @cards = @deck.cards
    @card = @deck.cards.new
  end

  def show
    @deck = Deck.find(params[:id])
    @deck.last_touched = DateTime.now
    @deck.save
    if @deck.cards [] # == ? 
      @card = @deck.cards.first
    else
      @card = @deck.cards.new
    end
    redirect_to deck_card_path(@deck, @card)
  end

  def update
    @deck = Deck.find(params[:id])
    if params[:published] = true
      if @deck.cards.length >= 5 # this is a great candidate for a custom validation
	# check out http://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations
        if @deck.update(deck_params)
          flash[:notice] = "Deck has been updated."
          redirect_to edit_deck_path(@deck.id)
        else
          redirect_to edit_deck_path(@deck.id)
        end
      else
          flash[:notice] = "You must have at least 5 cards before publishing."
          redirect_to edit_deck_path(@deck.id)
      end
    else
      if @deck.update(deck_params)
        flash[:notice] = "Deck has been updated."
        redirect_to edit_deck_path(@deck.id)
      end
    end
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to user_decks_path(current_user.id)
  end

  private

  def deck_params
    params.require(:deck).permit(:title, :published, :last_touched)
  end

  def card_params
    params.require(:card).permit(:question, :answer)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def create
   # remove unused code
  end

  def new
    @deck = Deck.find(params[:deck_id])
    @subject = @deck.subjects.find(params[:subject_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<% form_for [@deck, @card] do |f| %>
  <!-- if you add AR validations, you can explain here why something cannot be created -->

  <%= f.label :question %>
  <%= f.text_area :question %>

  <%= f.label :answer %>
  <%= f.text_area :answer %>

  <%= f.submit %>

<% end %>

app/views/cards/index.html.erb
Hello from Cards/Index

app/views/cards/new.html.erb
<h2>Add Card</h2>

app/views/cards/show.html.erb
<h1> <%= @deck.title %> (<%= @deck.cards.index(@card)+1%>/<%= @deck.cards.length %>) </h1>


<div class= "showwrapper">
  <div class="navleft navshows">
    <%= link_to image_tag('left_arrow_transparent.png', size:"50", id: "leftbutton"), deck_card_path(@deck, @cardprevious) %>
  </div>

  <div id= "test2">
    <div class="card effect__click" id= "test">
      <div class="card__front">
        <span class="cardshow card__text">
          <%= @card.question %>
        </span>
      </div>
      <div class="card__back">
        <span class="cardshow card__text">
          <%= @card.answer %>
        </span>
      </div>
    </div>
  </div>

  <div class="navright navshows">
    <%= link_to image_tag('right_arrow_transparent.png', size:"50", id: "rightbutton"), deck_card_path(@deck, @cardnext) %>
  </div>
</div>

app/views/decks/_form.html.erb
<%= form_for @deck do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/decks/edit.html.erb
<div class="editpage">


<%= form_for @deck do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.check_box :published %>
  <%= label_tag(:published, "Published?") %>
  <%= f.submit %>
<% end %>

<h3> Add Cards To Your Deck </h3>

<h3>Import Cards:</h3>
  <%= form_tag import_deck_cards_path(@deck), multipart: true do %>
  <%= file_field_tag :file, id:"filefieldtag" %>
  <%= submit_tag "Import from CSV"%>
  <% end %>

<h3> Add/Edit Manually :</h3>
<table >
    <td>
      Question
    </td>
    <td>
      Answer
    </td>
    <td>
      Edit
    </td>
    <td>
    </td>
  </tr>
  <% @cards.reverse.each do |card| %>
    <tr id= "cardform">
      <%= form_for [@deck, card] do |f| %>
      <td>
        <%= f.text_area :question, :id => "styled" %>
      </td>
      <td>
        <%= f.text_area :answer, :id => "styled" %>
      </td>
      <td>
        <%= f.submit %>
      </td>
      <% end %>
      <% if card.id %>
      <td> <%= button_to "Delete Card", deck_card_path(@deck, card), method: :delete, class: 'delete', :id => "deleteButton" %> </td>
      <% end %>
    </tr>
  <% end %>
</table>
</div>

app/views/decks/index.html.erb
<% @decks.each do |deck| %>
<div class="decks_home">
  <div class="card effect__click" id="card">
    <div class="card__front">
      <span class="card__text">
        <h4>Sample Card </h4>
      <%= deck.cards.first.question %>
      </span>
    </div>
    <div class="card__back">
      <span class="card__text">
        <h4>Sample Card </h4>
      <%= deck.cards.first.answer %>
      </span>
    </div>
  </div>
  <div class="qblockright">
    <h2> <%= link_to deck.title, deck_path(deck) %> </h2>
    Number of Cards: <%= deck.cards.length %> </br>
    Authored By: <%= deck.user.email %> </br>
    Last Dealt: <%= deck.last_touched.strftime("%m/%d/%Y") %>
  </div>
</div>
<% end %>

app/views/decks/new.html.erb
<h3> Add New Deck</h3>
  <%= form_for [@user, @deck] do |f| %>
    <!-- or render the partial here? -->
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
  <% end %>
<h3> Manage Decks </h3>
<table>
  <!-- I recommend using CSS to layout this form. Use tables for tabular data.. -->
  <tr>
    <td>
      Name of Deck
    </td>
    <td>
      Number of Cards
    </td>
    <td>
      Last Accessed
    </td>
    <td>
      Deck Settings
    </td>
    <td>
      Published?
    </td>
  </tr>
  <% @decks.each do |deck| %>
  <tr>
    <td><%= deck.title %></td>
    <td><%= deck.cards.length %> </td>
    <td><%= deck.last_touched.strftime("%m/%d/%Y") %> </td>
    <td><%= link_to "Edit", edit_deck_path(deck) %>/<%= link_to "Delete", deck_path(deck), method: :delete, class: 'delete' %> </td>
    <td>
    <% if deck.published %>
    <%= "Public" %>
    <% else %>
    <%= "Private" %>
    <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/decks/show.html.erb
<!-- remove unused files -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashCardsPlus</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header>
    <nav>
      <%= link_to "Home", decks_path %>
      <% if current_user %>
        <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
        <%= link_to 'Manage Decks', user_decks_path(current_user.id) %>
      <% else %>
        <%= link_to 'Signup', new_user_registration_path %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </nav>
</header>
<body data-no-turbolink="true">
  <!-- ^^ nice! I usually just remove turbolinks entirely- http://blog.steveklabnik.com/posts/2013-06-25-removing-turbolinks-from-rails-4 -->
  <h1>Flashcards Plus</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for [@deck, @subject] do |f| %>


<% end %>

app/views/subjects/new.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% @decks.each do |deck| %>
<%= @deck.title %>
<% end %>